name: AutoDeploy For API

on:
  push:
    branches:
      - 'dev'
      - 'master'

jobs:
  deploy_dev:
    name: "Деплой на машину 🔨"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to dev machine
        run: |
          sshpass -p ${{ secrets.MACHINE_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.MACHINE_USER }}@${{ secrets.MACHINE_HOST }} "cd /root/procollege-api && git pull"
          sleep 1
          sshpass -p ${{ secrets.MACHINE_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.MACHINE_USER }}@${{ secrets.MACHINE_HOST }} "systemctl restart procollege_api"

      - name: Escape bad symbols in variables
        id: escape_vars
        run: |
          message="${{ github.event.head_commit.message }}"
          actor="${{ github.actor }}"
          branch="${{ github.ref_name }}"

          escaped_message=$(echo "$message" | sed 's/[&~\`\*\_\[\]()#\+\-\=\|\{\}\.\!]/\\&/g')
          escaped_actor=$(echo "$actor" | sed 's/[&~\`\*\_\[\]()#\+\-\=\|\{\}\.\!]/\\&/g')
          escaped_branch=$(echo "$branch" | sed 's/[&~\`\*\_\[\]()#\+\-\=\|\{\}\.\!]/\\&/g')

          echo "escaped_message=$escaped_message" >> $GITHUB_ENV
          echo "escaped_actor=$escaped_actor" >> $GITHUB_ENV
          echo "escaped_branch=$escaped_branch" >> $GITHUB_ENV

      - name: Send Telegram Message
        run: |
          echo '🔨 *Backend deploy* 🔨\n\n>${{ env.escaped_message }}\n_by [${{ env.escaped_actor }}](https://github.com/${{ env.escaped_actor }})_ at `${{ env.escaped_branch }}`\n\n[commit link](${{ github.event.head_commit.url }})'
          curl \
            --data-urlencode 'chat_id=${{ secrets.TELEGRAM_CHAT_ID }}' \
            --data-urlencode 'message_thread_id=${{ secrets.TELEGRAM_MESSAGE_THREAD_ID }}' \
            --data-urlencode 'link_preview_options={"url":"${{ github.event.head_commit.url }}"}' \
            --data-urlencode 'parse_mode=markdownv2' \
            --data-urlencode $'text=🔨 *Backend deploy* 🔨\n\n>${{ env.escaped_message }}\n_by [${{ env.escaped_actor }}](https://github.com/${{ env.escaped_actor }})_ at `${{ env.escaped_branch }}`\n\n[commit link](${{ github.event.head_commit.url }})' \
            curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage"
